os: osx
osx_image: xcode12.2
language: swift
script:
- pod install
- xcodebuild clean build test -workspace PodcastPlayer.xcworkspace -scheme "CI" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.5,name=iPhone 11"  CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
